version: "3.9"

services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong)_1_(Password"
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uv-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mssql+pymssql://sa:yourStrong)_1_(Password@db:1433/master
      Redis_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_KEY: ${LANGSMITH_KEY}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      EMBEDD_MODEL: ${EMBEDD_MODEL}
      GPT_MODEL: ${GPT_MODEL}
      VECTOR_STORE_ADDRESS: ${VECTOR_STORE_ADDRESS}
      VECTOR_STORE_KEY: ${VECTOR_STORE_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
   

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  dbadmin:
    image: adminer
    container_name: dbadmin
    ports:
      - "5050:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mssql_data:

